# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozorestapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountAmount', models.FloatField(default=0)),
                ('accountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseTime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('expenseType', models.CharField(choices=[('food', 'food'), ('education', 'education'), ('travel', 'travel'), ('shopping', 'shopping'), ('extra', 'extra'), ('living', 'living')], default='extra', max_length=20)),
                ('expenseItem', models.CharField(max_length=100)),
                ('expenseAmount', models.FloatField()),
                ('expenseUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(choices=[('refund', 'Refundable Transaction'), ('nonrefund', 'Non Refundable Transaction')], default='nonrefund', max_length=20)),
                ('transactionAmount', models.FloatField()),
                ('transactionStatus', models.BooleanField()),
                ('fromUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionFrom', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactionTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
