# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozorestapi', '0002_account_expenses_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='google_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.URLField(default='null'),
        ),
    ]
