# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozorestapi', '0003_auto_20170822_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='facebook_id',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='google_id',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.URLField(blank=True, default='null'),
        ),
    ]
