# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozorestapi', '0004_auto_20170823_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.CharField(blank=True, default='null', max_length=300),
        ),
    ]
